name: Dan Portnoy
favicon: null
layout_spectrum: 0.48314
typography_spectrum: 0.35849
title: ViewFinder
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-288262-17
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d2dfe6'
    - '#121318'
    - '#5a6579'
    - '#788aa6'
    - '#3e4956'
  brandStrength: 0
  lightness: 0.4375
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
