name: DanPortnoy
favicon: null
layout_spectrum: 1
typography_spectrum: 0.35849
title: ViewFinder
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-288262-17
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d2dfe6'
    - '#121318'
    - '#5a6579'
    - '#788aa6'
    - '#3e4956'
  brandStrength: 0.40944066271185875
  lightness: 0.449528876459226
  saturation: 0.0290308038238436
  rhythmicContrast: 0.39425407792441547
purpose: []
